export const actionTypes = {
  //user Types
  GET_ALL_USERS: "GET_ALL_USERS",
  GET_ONE_USER_DETAIL: "GET_ONE_USER_DETAIL",
  //LOGIN_OR_REGISTER_ONE_USER: "LOGIN_OR_REGISTER_AN_USER",
  //UPDATE_ONE_USER: "UPDATE_AN_USER",
  //DELETE_ONE_USER: "DELETE_AN_USER",
  FILTER_USERS: "FILTER_USERS",
  USER_ROLE: 'USER_ROLE',

  //Apartment Types
  GET_ALL_APARTMENTS: "GET_ALL_APARTMENTS",
  GET_AN_APARTMENT_DETAIL: "GET_ONE_APARTMENT",
  CREATE_AN_APARTMENT: "CREATE_AN_APARTMENT",
  DELETE_AN_APPARTMENT: "DELETE_AN_APPARTMENT",
  UPDATE_AN_APARTMENT: "UPDATE_AN_APARTMENT",
  FILTER_APARTMENTS: "FILTER_APARTMENTS",
  GET_ALL_CITIES: "GET_ALL_CITIES",
  SET_SELECTED_CITY: "SET_SELECTED_CITY",
  GET_ALL_RENT_APARTMENTS: "GET_ALL_RENT_APARTMENTS",
  GET_ALL_SALE_APARTMENTS: "GET_ALL_SALE_APARTMENTS",
  GET_APARTMENTS_BY_PRICE_RANGE: 'GET_APARTMENTS_BY_PRICE_RANGE',
  SET_FILTERS: 'SET_FILTERS',
  GET_RATINGS: 'GET_RATINGS'
};
